[project]
name = "blackjack-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pyfiglet>=1.0.4",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
]
